import type { Metadata } from "next";
import { Refresher } from "cms-renderer/lib/refresher";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Refresher
          cmsUrl="https://cms.dev.tryprofound.com"
          websiteId="79539651-e362-4f54-ba15-608dd267f883"
          apiKey="sk_NW1mZ9cD9bExJpTPkodLw3rk0sISAwuLHxgod55wG0lPeX"
        />
        {children}
      </body>
    </html>
  );
}
